create table IF NOT EXISTS upload_list  (
item_id        	 	 INTEGER,
userId    INTEGER,
create_time          TIMESTAMP not null,
title                VARCHAR(1000),
intro				 VARCHAR(5000),
price                DEC(10,2),
retail_price         DEC(10,2),
markUpValue  DEC(10,2),
group_deal_count  INTEGER 						default 0,
upload_type INTEGER,
is_copy TEXT,
uploadStatus TEXT,
message TEXT,
cover        		 TEXT,
supplyInfo_list   TEXT,
products_list         TEXT,
tags_list TEXT,
stalls_list TEXT,
category_list TEXT,
property_list TEXT,
images_list        		TEXT,
videos_list TEXT,
color_pics_list TEXT,
material_list TEXT,
age_list TEXT,
style_list TEXT,
season_list TEXT,
extend_property_type_list TEXT,
remark TEXT,
discount  DEC(10,2)
);